import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import CoffeeForm from '../components/Form/CoffeeForm'
import { Box, List, ListItemText, Grid, CircularProgress } from '@mui/material'
import { useEvents } from '../contexts/Events/hooks'

export default function HomePage() {
  const { events, eventsQuery } = useEvents()
  return (
    <div className={styles.container}>
      <Head>
        <title>Buy Me A Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container>
          <Grid
            container
            item
            md={6}
            alignItems="start"
            justifyContent="center"
          >
            <Box>
              <h1 className={styles.title}>Buy Me A Coffee ☕️</h1>
              <Box
                sx={{
                  marginTop: '20px',
                  width: '100%',
                }}
              >
                <CoffeeForm />
              </Box>
            </Box>
          </Grid>
          <Grid
            container
            item
            md={6}
            alignItems="start"
            justifyContent="center"
          >
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                margin: 'auto',
              }}
            >
              {eventsQuery?.isFetched ? (
                <div>
                  <h2>Messages:</h2>
                  <List sx={{ height: '700px', overflowY: 'scroll' }}>
                    {events?.map((item, index) => (
                      <Box
                        key={index}
                        sx={{
                          margin: '10px 0',
                          border: '1px solid #000',
                          padding: '5px',
                          borderRadius: '10px',
                        }}
                      >
                        <ListItemText>
                          Accounts:{' '}
                          {`${item.account.slice(0, 6)}...${item.account.slice(
                            -4,
                          )}`}
                        </ListItemText>
                        <ListItemText>Name: {item.name}</ListItemText>
                        <ListItemText>Msgs: {item.messages}</ListItemText>
                      </Box>
                    ))}
                  </List>
                </div>
              ) : (
                <CircularProgress size={50} />
              )}
            </Box>
          </Grid>
        </Grid>
      </main>
    </div>
  )
}
